"""fix_langchain_tables

Revision ID: 2020889f18c5
Revises: 7746e6d6d3c3
Create Date: 2025-07-22 13:09:58.432515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2020889f18c5'
down_revision: Union[str, Sequence[str], None] = '7746e6d6d3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_langchain_pg_collection_uuid', 'langchain_pg_collection', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_langchain_pg_collection_uuid'), 'langchain_pg_collection', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
