"""fix_langchain_tables

Revision ID: 96f31b00d98e
Revises: d5abbcd7aafc
Create Date: 2025-07-22 13:21:39.375802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '96f31b00d98e'
down_revision: Union[str, Sequence[str], None] = 'd5abbcd7aafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(op.f('uq_langchain_pg_collection_uuid'), 'langchain_pg_collection', type_='unique')
    op.alter_column('langchain_pg_embedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('langchain_pg_embedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_langchain_pg_collection_uuid'), 'langchain_pg_collection', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
