"""fix_langchain_tables

Revision ID: d5abbcd7aafc
Revises: 2020889f18c5
Create Date: 2025-07-22 13:18:19.109231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5abbcd7aafc'
down_revision: Union[str, Sequence[str], None] = '2020889f18c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
#op.drop_constraint(op.f('uq_langchain_pg_collection_uuid'), 'langchain_pg_collection', type_='unique')
    op.add_column('langchain_pg_embedding', sa.Column('custom_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('langchain_pg_embedding', 'custom_id')
    op.create_unique_constraint(op.f('uq_langchain_pg_collection_uuid'), 'langchain_pg_collection', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
